name: 'dbt_project_target_board'
version: '1.0.0'
config-version: 2

profile: 'user_profile'

seed-paths: ["seeds"]
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
